# Generated by Django 3.0.3 on 2020-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=20)),
            ],
        ),
    ]
